# dev-开发环境，test-测试环境
spring:
  profiles:
    active: dev

# 配置日志 log-impl：日志实现
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml
