#dev-开发环境 test-测试环境 prod-生产环境

server:
  port: 8081

# 数据库连接配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatisplus?useUnicode=true?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver