server:
  port: 8085

# slf4j 配置
# logback 日志配置文件；level 日志输出级别
#logging:
 # config: classpathlogback.xml
  #level:
   # com.itcodai.course03.dao: trace

spring:
  # redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    # 用 0号 redis数据库
    database: 0
    # 连接池配置
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
